version: "3.3"

services:
  nats:
    image: nats-server-local
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret
    command: /gnatsd -c gnatsd.conf

  client:
    image: nats-server-local
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret
    command: /main

secrets:
  nats_username_secret:
    file: ./devsecrets/nats_username_secret
  nats_password_secret:
    file: ./devsecrets/nats_password_secret
